
# This file is part of the dinNewsPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinNewsPlugin model configuration
#
# @package     dinNewsPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>
models:
    DinNews:
        columns:
            state_id:
                disable:        true

filters:

    DinNewsCategoryTranslation:
        disable:                true

    DinNewsTranslation:
        disable:                true

#EOF