
# This file is part of the dinNewsPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinNewsPlugin routing configuration
#
# @package     dinNewsPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

din_news_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinNews'
        module:                 'dinNewsAdmin'
        prefix_path:            '/adm/news'
        column:                 'id'
        with_wildcard_routes:   true

din_news_category_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinNewsCategory'
        module:                 'dinNewsCategoryAdmin'
        prefix_path:            '/adm/news/category'
        column:                 'id'
        with_wildcard_routes:   true

#EOF